language: generic
sudo: required
dist: trusty
branches:
  only:
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make build VERSION=$TRAVIS_TAG
deploy:
- provider: releases
  prerelease: true
  skip_cleanup: true
  file_glob: true
  file: "./*.zip"
  on:
    tags: true
    all_branches: true
  api_key:
    secure: bOaoJIWQzT5Vd2WyIkSNM3oBDnZM27WRnIsLLUTp4XscQ3G4PGwZ6OfpjvIGb9zXbv3uLSQ63A1NiulVVryMZWSVDr0awzxcYjY1p8hMztuav2CPYUOgkTWtuWAsIbsNOFw+A3dsWfCHJs+jOuIiSnD21ic8ppcjyaag43cfrJYV1ERLP1PLqC2Sk1GEoJi9NpbcmE7jLr1VDec1PJ5NENt7Ot68+a218nSCMyGZFQ67lNDgcxKF+53xMEJXZ4lxmqsOklhUqmhLIn72BuzgrNcLo7Stc/sBHqKqeJSheWZ1qWEfcxcKzlTaW3uJwjtAey+01FU2QeI8dgLzXa0dKH9/a5MC5c5isqjBpKgBzlWl4hHvOxWV+ElpJg6UNwVwjzSReTNscFdOxiI5lgcZ2H43kRYjS+y+SkGPmtyt7d1NXUjPu3SNl8LNQwUtb8w6cm74B5+Rd2ME9ADNI8EyDJL27I/q7MaZ8egcaGJ2duW9zMNJ+2KMhg6M2RLsh+SAz7ya68KlsFqTHUfbIu0IszsTVfF1TJ8CXhhNCpknQ8dhS5yu9E2RermOmtwDAlbzzLzEZr7kovFasUIGzK7eBuatJ+Ph7Vo28f1birQ1mpcRqJOJwzlWG04b+5ZXc4HzcdDmCH4G+TM51S4gSw9TasuY2XuAhLeRIepoULva/sI=
